export const ARRAY_CAVALLE = [
  { name: 'Ilaria', image: 'assets/img/ilaria.jpg', voto: 85 },
  { name: 'Giomi', image: 'assets/img/giomi.jpg', voto: 80 },
  { name: 'Galletti', image: 'assets/img/galletti.jpg', voto: 80 },
  { name: 'Asia', image: 'assets/img/asia.jpg', voto: 95 },
  { name: 'Amato', image: 'assets/img/amato.jpg', voto: 65 },
  { name: 'Bubby', image: 'assets/img/bubby.jpg', voto: 68 },
  { name: 'Caccia', image: 'assets/img/caccia.jpg', voto: 75 },
  { name: 'Camma', image: 'assets/img/camma.jpg', voto: 90 },
  { name: 'Evangelion', image: 'assets/img/evangelion.jpg', voto: 88 },
  { name: 'Gdv', image: 'assets/img/gdv.jpg', voto: 75 },
  { name: 'Greca', image: 'assets/img/lagreca2.jpg', voto: 80 },
  { name: 'Gretarossi', image: 'assets/img/gretarossi.jpg', voto: 95 },
  { name: 'Guerrini', image: 'assets/img/guerrini.jpg', voto: 80 },
  { name: 'Klea', image: 'assets/img/klea.jpg', voto: 98 },
  { name: 'Mani', image: 'assets/img/mani.jpg', voto: 85 },
  { name: 'Marialaura', image: 'assets/img/marialaura.jpg', voto: 78 },
  { name: 'Minguzzi', image: 'assets/img/minguzzi.jpg', voto: 80 },
  { name: 'Minzi', image: 'assets/img/minzi.jpg', voto: 85 },
  { name: 'Molduc', image: 'assets/img/molduc.jpg', voto: 85 },
  { name: 'Mommy', image: 'assets/img/mommy.jpg', voto: 70 },
  { name: 'Podda', image: 'assets/img/podda.jpg', voto: 67 },
  { name: 'Sofi', image: 'assets/img/sofi.jpg', voto: 80 },
  { name: 'Spinella', image: 'assets/img/spinella.jpg', voto: 93 },
  { name: 'Trioschi', image: 'assets/img/trioschi.jpg', voto: 80 },
  { name: 'Vasi', image: 'assets/img/vasi.jpg', voto: 60 },
  { name: 'Bagnoli', image: 'assets/img/bagnoli.jpg', voto: 80 },
  { name: 'Cico', image: 'assets/img/cico.jpg', voto: 73 },
  { name: 'Dalpozzo', image: 'assets/img/dalpozzo.jpg', voto: 90 },
  { name: 'Danielina', image: 'assets/img/danielina.jpg', voto: 83 },
  { name: 'Devellis', image: 'assets/img/devellis.jpg', voto: 75 },
  { name: 'Echi', image: 'assets/img/echi.jpg', voto: 80 },
  { name: 'Gemma', image: 'assets/img/gemma.jpg', voto: 75 },
  { name: 'Bucci', image: 'assets/img/bucci.jpg', voto: 80 },
  { name: 'Cavalli', image: 'assets/img/cavalli.jpg', voto: 80 },
  { name: 'Garroni', image: 'assets/img/garroni.jpg', voto: 65 },
  { name: 'Levriero', image: 'assets/img/levriero.jpg', voto: 60 },
  { name: 'SaraPale', image: 'assets/img/sarapale.jpg', voto: 60 },
  { name: 'Savva', image: 'assets/img/savva.jpg', voto: 80 },
  { name: 'Simo', image: 'assets/img/simo2.jpg', voto: 65 },
  { name: 'Zaffi', image: 'assets/img/zaffi.jpg', voto: 85 },
  { name: 'Zefi', image: 'assets/img/zefi.jpg', voto: 75 },
  { name: 'SofiRossi', image: 'assets/img/sofirossi.jpg', voto: 90 },
  { name: 'Danesi', image: 'assets/img/danesi.jpg', voto: 75 },
  { name: 'Gallamini', image: 'assets/img/gallamini.jpg', voto: 78 },
  { name: 'GiuliaPale', image: 'assets/img/giuliapale.jpg', voto: 75 },
  { name: 'Hillary', image: 'assets/img/hillary.jpg', voto: 85 },
  { name: 'Savorelli', image: 'assets/img/savorelli.jpg', voto: 65 },
  { name: 'Syria', image: 'assets/img/syria.jpg', voto: 85 },
  { name: 'Verdi', image: 'assets/img/verdi2.jpg', voto: 85 },
  { name: 'Baravelli', image: 'assets/img/baravelli.jpg', voto: 82 },
  { name: 'Garavini', image: 'assets/img/garavini.jpg', voto: 83 },
  { name: 'Luciacosta', image: 'assets/img/luciacosta.jpg', voto: 70 },
  { name: 'Magnani', image: 'assets/img/magnani.jpg', voto: 75 },
  { name: 'Sofipale', image: 'assets/img/sofipale.jpg', voto: 85 },
  { name: 'Brusi', image: 'assets/img/brusi.jpg', voto: 0 },
  { name: 'Fantini', image: 'assets/img/fantini.jpg', voto: 0 },
  { name: 'Gine', image: 'assets/img/gine.jpg', voto: 0 },
  { name: 'Marrico', image: 'assets/img/marrico.jpg', voto: 0 },
  { name: 'Masotti', image: 'assets/img/masotti.jpg', voto: 0 },
  { name: 'Rebbireb', image: 'assets/img/rebbireb.jpg', voto: 0 },
  { name: 'RusalenGrande', image: 'assets/img/rusalenGrande.jpg', voto: 0 },
  { name: 'RusalenPiccola', image: 'assets/img/rusalenPiccola.jpg', voto: 0 },
  { name: 'Burattoni', image: 'assets/img/burattoni.jpg', voto: 0 },
  { name: 'Caterinone', image: 'assets/img/caterinone.jpg', voto: 0 },
  { name: 'Dayanacambi', image: 'assets/img/dayanacambi.jpg', voto: 0 },
  { name: 'Evangelista', image: 'assets/img/evangelista.jpg', voto: 0 },
  { name: 'Giuliatamarra', image: 'assets/img/giuliatamarra.jpg', voto: 0 },
  { name: 'orsi', image: 'assets/img/orsi.jpg', voto: 0 },
  { name: 'Moretto', image: 'assets/img/moretto.jpg', voto: 0 },
  { name: 'Pagnini', image: 'assets/img/pagnini.jpg', voto: 0 },
  { name: 'Secrieru', image: 'assets/img/secrieru.jpg', voto: 0 },
  { name: 'Vaglio', image: 'assets/img/vaglio.jpg', voto: 0 },
  { name: 'Zanolli', image: 'assets/img/zanolli.jpg', voto: 0 },
  { name: 'Celeste Lolli', image: 'assets/img/celesteLoli.jpg', voto: 0 },
  { name: 'Clara Cavallucci', image: 'assets/img/claraCavallucci.jpg', voto: 0 },
  { name: 'Giulia Valeriani', image: 'assets/img/giuliaValeriani.jpg', voto: 0 },
  { name: 'Letality', image: 'assets/img/letality.jpg', voto: 0 },
  { name: 'Livia Tura', image: 'assets/img/liviaTura.jpg', voto: 0 },
  { name: 'Maltucci M', image: 'assets/img/maltucciM.jpg', voto: 0 },
  { name: 'Meowtwo', image: 'assets/img/meowtwo.jpg', voto: 0 },
  { name: 'Molducci God', image: 'assets/img/molduccigod.jpg', voto: 0 },
  { name: 'Serena Romano', image: 'assets/img/serenaRomano.jpg', voto: 0 },
  { name: 'Sofi Sticata', image: 'assets/img/sofiSticata.jpg', voto: 0 },
  { name: 'Yarmila Mani', image: 'assets/img/yarmilamani.jpg', voto: 0 },
  { name: 'Barboni', image: 'assets/img/barboni.jpg', voto: 0 },
  { name: 'Bresciani', image: 'assets/img/bresciani.jpg', voto: 0 },
  { name: 'Gabrielli', image: 'assets/img/gabrielli.jpg', voto: 0 },
  { name: 'Galavotti', image: 'assets/img/galavotti.jpg', voto: 0 },
  { name: 'Levriero 2', image: 'assets/img/levriero2.jpg', voto: 0 },
  { name: 'Lisa P', image: 'assets/img/lisap.jpg', voto: 0 },
  { name: 'Pagliarani', image: 'assets/img/pagliarani.jpg', voto: 0 },
  { name: 'Parisi', image: 'assets/img/parisi.jpg', voto: 0 },
  { name: 'Sintucci', image: 'assets/img/sintucci.jpg', voto: 0 },
  { name: 'Zigliotto', image: 'assets/img/zigliotto.jpg', voto: 0 },
  { name: 'Anna Giulia Fenati', image: 'assets/img/annaGiuliaFenati.jpg', voto: 0 },
  { name: 'Arianna Plazzi', image: 'assets/img/ariannaPlazzi.jpg', voto: 0 },
  { name: 'Ballarin', image: 'assets/img/ballarin.jpg', voto: 0 },
  { name: 'Bojana', image: 'assets/img/bojana.jpg', voto: 0 },
  { name: 'Elena Michieletti', image: 'assets/img/elenaMichieletti.jpg', voto: 0 },
  { name: 'Fra Bertoni', image: 'assets/img/fraBertoni.jpg', voto: 0 },
  { name: 'Giorgia Berti', image: 'assets/img/giorgiaBerti.jpg', voto: 0 },
  { name: 'Ivana', image: 'assets/img/ivana.jpg', voto: 0 },
  { name: 'Kassandra Marrali', image: 'assets/img/kassandraMarrali.jpg', voto: 0 },
  { name: 'Leti96', image: 'assets/img/leti96.jpg', voto: 0 },
  { name: 'Maenza', image: 'assets/img/maenza.jpg', voto: 0 },
  { name: 'Margherita Model', image: 'assets/img/margheritaModel.jpg', voto: 0 },
  { name: 'Sofia Mihai', image: 'assets/img/sofiaMihai.jpg', voto: 0 },
  { name: 'Tiene', image: 'assets/img/tiene.jpg', voto: 0 }


];


export const ARRAY_CAVALLE_CON_STATS2 = [
  {
    "name": "Ilaria",
    "image": "assets/img/ilaria.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 8,
    "tette": 4,
    "sensualita": 9,
    "intelligenza": 8,
    "maiala": 9
  },
  {
    "name": "Giomi",
    "image": "assets/img/giomi.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 9,
    "tette": 3,
    "sensualita": 8,
    "intelligenza": 5,
    "maiala": 5
  },
  {
    "name": "Galletti",
    "image": "assets/img/galletti.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 8,
    "culo": 8,
    "tette": 6,
    "sensualita": 6,
    "intelligenza": 6,
    "maiala": 7
  },
  {
    "name": "Asia",
    "image": "assets/img/asia.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 9,
    "tette": 8,
    "sensualita": 10,
    "intelligenza": 2,
    "maiala": 5
  },
  {
    "name": "Amato",
    "image": "assets/img/amato.jpg",
    "voto": 6,
    "faccia": 2,
    "corpo": 8,
    "culo": 6,
    "tette": 10,
    "sensualita": 9,
    "intelligenza": 3,
    "maiala": 8
  },
  {
    "name": "Bubby",
    "image": "assets/img/bubby.jpg",
    "voto": 6,
    "faccia": 8,
    "corpo": 8,
    "culo": 2,
    "tette": 6,
    "sensualita": 7,
    "intelligenza": 3,
    "maiala": 5
  },
  {
    "name": "Caccia",
    "image": "assets/img/caccia.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 5,
    "culo": 4,
    "tette": 2,
    "sensualita": 7,
    "intelligenza": 6,
    "maiala": 9
  },
  {
    "name": "Camma",
    "image": "assets/img/camma.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 10,
    "tette": 2,
    "sensualita": 8,
    "intelligenza": 6,
    "maiala": 2
  },
  {
    "name": "Evangelion",
    "image": "assets/img/evangelion.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 10,
    "tette": 8,
    "sensualita": 9,
    "intelligenza": 5,
    "maiala": 7
  },
  {
    "name": "Gdv",
    "image": "assets/img/gdv.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 8,
    "culo": 9,
    "tette": 2,
    "sensualita": 2,
    "intelligenza": 8,
    "maiala": 1
  },
  {
    "name": "Greca",
    "image": "assets/img/lagreca2.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 8,
    "culo": 6,
    "tette": 10,
    "sensualita": 6,
    "intelligenza": 3,
    "maiala": 5
  },
  {
    "name": "Gretarossi",
    "image": "assets/img/gretarossi.jpg",
    "voto": 9,
    "faccia": 10,
    "corpo": 10,
    "culo": 10,
    "tette": 4,
    "sensualita": 10,
    "intelligenza": 3,
    "maiala": 6
  },
  {
    "name": "Guerrini",
    "image": "assets/img/guerrini.jpg",
    "voto": 8,
    "faccia": 4,
    "corpo": 9,
    "culo": 10,
    "tette": 5,
    "sensualita": 7,
    "intelligenza": 2,
    "maiala": 8
  },
  {
    "name": "Klea",
    "image": "assets/img/klea.jpg",
    "voto": 10,
    "faccia": 9,
    "corpo": 10,
    "culo": 9,
    "tette": 10,
    "sensualita": 10,
    "intelligenza": 4,
    "maiala": 10
  },
  {
    "name": "Mani",
    "image": "assets/img/mani.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 9,
    "tette": 9,
    "sensualita": 8,
    "intelligenza": 5,
    "maiala": 6
  },
  {
    "name": "Marialaura",
    "image": "assets/img/marialaura.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 7,
    "culo": 7,
    "tette": 8,
    "sensualita": 8,
    "intelligenza": 8,
    "maiala": 8
  },
  {
    "name": "Minguzzi",
    "image": "assets/img/minguzzi.jpg",
    "voto": 7,
    "faccia": 6,
    "corpo": 7,
    "culo": 7,
    "tette": 9,
    "sensualita": 7,
    "intelligenza": 5,
    "maiala": 10
  },
  {
    "name": "Minzi",
    "image": "assets/img/minzi.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 8,
    "culo": 9,
    "tette": 9,
    "sensualita": 9,
    "intelligenza": 6,
    "maiala": 9
  },
  {
    "name": "Mommy",
    "image": "assets/img/mommy.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 5,
    "culo": 5,
    "tette": 10,
    "sensualita": 7,
    "intelligenza": 4,
    "maiala": 9
  },
  {
    "name": "Podda",
    "image": "assets/img/podda.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 7,
    "culo": 7,
    "tette": 3,
    "sensualita": 5,
    "intelligenza": 7,
    "maiala": 2
  },
  {
    "name": "Sofi",
    "image": "assets/img/sofi.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 9,
    "culo": 10,
    "tette": 8,
    "sensualita": 9,
    "intelligenza": 7,
    "maiala": 10
  },
  {
    "name": "Spinella",
    "image": "assets/img/spinella.jpg",
    "voto": 9,
    "faccia": 8,
    "corpo": 10,
    "culo": 10,
    "tette": 9,
    "sensualita": 9,
    "intelligenza": 5,
    "maiala": 8
  },
  {
    "name": "Trioschi",
    "image": "assets/img/trioschi.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 9,
    "culo": 6,
    "tette": 9,
    "sensualita": 7,
    "intelligenza": 7,
    "maiala": 9
  },
  {
    "name": "Vasi",
    "image": "assets/img/vasi.jpg",
    "voto": 6,
    "faccia": 8,
    "corpo": 4,
    "culo": 4,
    "tette": 7,
    "sensualita": 5,
    "intelligenza": 7,
    "maiala": 7
  },
  {
    "name": "Bagnoli",
    "image": "assets/img/bagnoli.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 7,
    "tette": 10,
    "sensualita": 8,
    "intelligenza": 2,
    "maiala": 8
  },
  {
    "name": "Cico",
    "image": "assets/img/cico.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 8,
    "culo": 9,
    "tette": 2,
    "sensualita": 7,
    "intelligenza": 9,
    "maiala": 8
  },
  {
    "name": "Dalpozzo",
    "image": "assets/img/dalpozzo.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 10,
    "culo": 9,
    "tette": 10,
    "sensualita": 9,
    "intelligenza": 2,
    "maiala": 10
  },
  {
    "name": "Danielina",
    "image": "assets/img/danielina.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 9,
    "culo": 8,
    "tette": 3,
    "sensualita": 8,
    "intelligenza": 8,
    "maiala": 8
  },
  {
    "name": "Devellis",
    "image": "assets/img/devellis.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 9,
    "culo": 9,
    "tette": 7,
    "sensualita": 6,
    "intelligenza": 8,
    "maiala": 9
  },
  {
    "name": "Echi",
    "image": "assets/img/echi.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 9,
    "culo": 8,
    "tette": 7,
    "sensualita": 9,
    "intelligenza": 3,
    "maiala": 8
  },
  {
    "name": "Gemma",
    "image": "assets/img/gemma.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 8,
    "culo": 8,
    "tette": 2,
    "sensualita": 7,
    "intelligenza": 7,
    "maiala": 9
  },
  {
    "name": "Bucci",
    "image": "assets/img/bucci.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 9,
    "culo": 9,
    "tette": 1,
    "sensualita": 8,
    "intelligenza": 7,
    "maiala": 6
  },
  {
    "name": "Cavalli",
    "image": "assets/img/cavalli.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 9,
    "culo": 8,
    "tette": 8,
    "sensualita": 8,
    "intelligenza": 5,
    "maiala": 7
  },
  {
    "name": "Garroni",
    "image": "assets/img/garroni.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 7,
    "culo": 6,
    "tette": 3,
    "sensualita": 8,
    "intelligenza": 4,
    "maiala": 9
  },
  {
    "name": "Levriero",
    "image": "assets/img/levriero.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 7,
    "culo": 9,
    "tette": 1,
    "sensualita": 4,
    "intelligenza": 2,
    "maiala": 2
  },
  {
    "name": "SaraPale",
    "image": "assets/img/sarapale.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 8,
    "culo": 7,
    "tette": 6,
    "sensualita": 9,
    "intelligenza": 8,
    "maiala": 7
  },
  {
    "name": "Savva",
    "image": "assets/img/savva.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 9,
    "culo": 8,
    "tette": 2,
    "sensualita": 8,
    "intelligenza": 8,
    "maiala": 6
  },
  {
    "name": "Simo",
    "image": "assets/img/simo2.jpg",
    "voto": 6,
    "faccia": 6,
    "corpo": 7,
    "culo": 8,
    "tette": 8,
    "sensualita": 4,
    "intelligenza": 5,
    "maiala": 8
  },
  {
    "name": "Zaffi",
    "image": "assets/img/zaffi.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 9,
    "culo": 9,
    "tette": 3,
    "sensualita": 7,
    "intelligenza": 8,
    "maiala": 6
  },
  {
    "name": "Zefi",
    "image": "assets/img/zefi.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 9,
    "culo": 9,
    "tette": 6,
    "sensualita": 7,
    "intelligenza": 4,
    "maiala": 8
  },
  {
    "name": "SofiRossi",
    "image": "assets/img/sofirossi.jpg",
    "voto": 9,
    "faccia": 10,
    "corpo": 9,
    "culo": 8,
    "tette": 7,
    "sensualita": 9,
    "intelligenza": 7,
    "maiala": 4
  },
  {
    "name": "Danesi",
    "image": "assets/img/danesi.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 7,
    "culo": 7,
    "tette": 3,
    "sensualita": 5,
    "intelligenza": 7,
    "maiala": 2
  },
  {
    "name": "Gallamini",
    "image": "assets/img/gallamini.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 8,
    "culo": 8,
    "tette": 4,
    "sensualita": 7,
    "intelligenza": 7,
    "maiala": 5
  },
  {
    "name": "GiuliaPale",
    "image": "assets/img/giuliapale.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 8,
    "culo": 9,
    "tette": 2,
    "sensualita": 7,
    "intelligenza": 5,
    "maiala": 3
  },
  {
    "name": "Hillary",
    "image": "assets/img/hillary.jpg",
    "voto": 8,
    "faccia": 10,
    "corpo": 8,
    "culo": 7,
    "tette": 6,
    "sensualita": 8,
    "intelligenza": 8,
    "maiala": 5
  },
  {
    "name": "Savorelli",
    "image": "assets/img/savorelli.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 7,
    "culo": 6,
    "tette": 6,
    "sensualita": 6,
    "intelligenza": 6,
    "maiala": 8
  },
  {
    "name": "Syria",
    "image": "assets/img/syria.jpg",
    "voto": 9,
    "faccia": 7,
    "corpo": 10,
    "culo": 10,
    "tette": 8,
    "sensualita": 8,
    "intelligenza": 4,
    "maiala": 7
  },
  {
    "name": "Verdi",
    "image": "assets/img/verdi2.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 8,
    "culo": 8,
    "tette": 2,
    "sensualita": 8,
    "intelligenza": 5,
    "maiala": 6
  },
  {
    "name": "Baravelli",
    "image": "assets/img/baravelli.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 8,
    "culo": 8,
    "tette": 2,
    "sensualita": 7,
    "intelligenza": 7,
    "maiala": 6
  },
  {
    "name": "Garavini",
    "image": "assets/img/garavini.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 8,
    "culo": 9,
    "tette": 2,
    "sensualita": 7,
    "intelligenza": 7,
    "maiala": 7
  },
  {
    "name": "Luciacosta",
    "image": "assets/img/luciacosta.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 7,
    "culo": 8,
    "tette": 1,
    "sensualita": 6,
    "intelligenza": 8,
    "maiala": 9
  },
  {
    "name": "Magnani",
    "image": "assets/img/magnani.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 8,
    "culo": 7,
    "tette": 6,
    "sensualita": 7,
    "intelligenza": 6,
    "maiala": 8
  },
  {
    "name": "Sofipale",
    "image": "assets/img/sofipale.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 9,
    "tette": 9,
    "sensualita": 8,
    "intelligenza": 4,
    "maiala": 7
  },
  {
    "name": "Brusi",
    "image": "assets/img/brusi.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 8,
    "culo": 8,
    "tette": 6,
    "sensualita": 7,
    "intelligenza": 3,
    "maiala": 9
  },
  {
    "name": "Fantini",
    "image": "assets/img/fantini.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 8,
    "culo": 8,
    "tette": 7,
    "sensualita": 5,
    "intelligenza": 9,
    "maiala": 8
  },
  {
    "name": "Gine",
    "image": "assets/img/gine.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 8,
    "culo": 9,
    "tette": 7,
    "sensualita": 8,
    "intelligenza": 3,
    "maiala": 10
  },
  {
    "name": "Marrico",
    "image": "assets/img/marrico.jpg",
    "voto": 6,
    "faccia": 6,
    "corpo": 6,
    "culo": 6,
    "tette": 8,
    "sensualita": 2,
    "intelligenza": 9,
    "maiala": 10
  },
  {
    "name": "Masotti",
    "image": "assets/img/masotti.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 8,
    "culo": 8,
    "tette": 2,
    "sensualita": 7,
    "intelligenza": 1,
    "maiala": 7
  },
  {
    "name": "Rebbireb",
    "image": "assets/img/rebbireb.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 9,
    "tette": 4,
    "sensualita": 8,
    "intelligenza": 6,
    "maiala": 7
  },
  {
    "name": "RusalenGrande",
    "image": "assets/img/rusalenGrande.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 8,
    "culo": 8,
    "tette": 8,
    "sensualita": 8,
    "intelligenza": 4,
    "maiala": 5
  },
  {
    "name": "RusalenPiccola",
    "image": "assets/img/rusalenPiccola.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 9,
    "culo": 8,
    "tette": 5,
    "sensualita": 6,
    "intelligenza": 4,
    "maiala": 6
  },
  {
    "name": "Burattoni",
    "image": "assets/img/burattoni.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 8,
    "culo": 8,
    "tette": 5,
    "sensualita": 7,
    "intelligenza": 7,
    "maiala": 7
  },
  {
    "name": "Caterinone",
    "image": "assets/img/caterinone.jpg",
    "voto": 8,
    "faccia": 6,
    "corpo": 9,
    "culo": 8,
    "tette": 5,
    "sensualita": 7,
    "intelligenza": 7,
    "maiala": 9
  },
  {
    "name": "Dayanacambi",
    "image": "assets/img/dayanacambi.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 7,
    "culo": 8,
    "tette": 2,
    "sensualita": 7,
    "intelligenza": 4,
    "maiala": 8
  },
  {
    "name": "Evangelista",
    "image": "assets/img/evangelista.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 9,
    "tette": 8,
    "sensualita": 9,
    "intelligenza": 4,
    "maiala": 6
  },
  {
    "name": "Giuliatamarra",
    "image": "assets/img/giuliatamarra.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 8,
    "tette": 5,
    "sensualita": 7,
    "intelligenza": 2,
    "maiala": 9
  },
  {
    "name": "orsi",
    "image": "assets/img/orsi.jpg",
    "voto": 9,
    "faccia": 8,
    "corpo": 9,
    "culo": 9,
    "tette": 8,
    "sensualita": 9,
    "intelligenza": 5,
    "maiala": 10
  },
  {
    "name": "Moretto",
    "image": "assets/img/moretto.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 8,
    "culo": 8,
    "tette": 1,
    "sensualita": 8,
    "intelligenza": 2,
    "maiala": 9
  },
  {
    "name": "Pagnini",
    "image": "assets/img/pagnini.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 7,
    "tette": 3,
    "sensualita": 8,
    "intelligenza": 8,
    "maiala": 2
  },
  {
    "name": "Secrieru",
    "image": "assets/img/secrieru.jpg",
    "voto": 10,
    "faccia": 9,
    "corpo": 10,
    "culo": 10,
    "tette": 6,
    "sensualita": 9,
    "intelligenza": 3,
    "maiala": 5
  },
  {
    "name": "Vaglio",
    "image": "assets/img/vaglio.jpg",
    "voto": 9,
    "faccia": 8,
    "corpo": 9,
    "culo": 10,
    "tette": 9,
    "sensualita": 8,
    "intelligenza": 9,
    "maiala": 6
  },
  {
    "name": "Zanolli",
    "image": "assets/img/zanolli.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 9,
    "culo": 7,
    "tette": 7,
    "sensualita": 7,
    "intelligenza": 1,
    "maiala": 9
  },
  {
    "name": "Celeste Lolli",
    "image": "assets/img/celesteLoli.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 8,
    "tette": 8,
    "sensualita": 7,
    "intelligenza": 7,
    "maiala": 6
  },
  {
    "name": "Clara Cavallucci",
    "image": "assets/img/claraCavallucci.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 7,
    "culo": 5,
    "tette": 8,
    "sensualita": 6,
    "intelligenza": 7,
    "maiala": 9
  },
  {
    "name": "Giulia Valeriani",
    "image": "assets/img/giuliaValeriani.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 9,
    "culo": 7,
    "tette": 10,
    "sensualita": 8,
    "intelligenza": 1,
    "maiala": 10
  },
  {
    "name": "Letality",
    "image": "assets/img/letality.jpg",
    "voto": 7,
    "faccia": 3,
    "corpo": 8,
    "culo": 9,
    "tette": 9,
    "sensualita": 3,
    "intelligenza": 1,
    "maiala": 5
  },
  {
    "name": "Livia Tura",
    "image": "assets/img/liviaTura.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 8,
    "culo": 8,
    "tette": 2,
    "sensualita": 7,
    "intelligenza": 8,
    "maiala": 2
  },
  {
    "name": "Maltucci M",
    "image": "assets/img/maltucciM.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 7,
    "culo": 7,
    "tette": 2,
    "sensualita": 8,
    "intelligenza": 6,
    "maiala": 4
  },
  {
    "name": "Meowtwo",
    "image": "assets/img/meowtwo.jpg",
    "voto": 10,
    "faccia": 10,
    "corpo": 9,
    "culo": 9,
    "tette": 3,
    "sensualita": 10,
    "intelligenza": 2,
    "maiala": 9
  },
  {
    "name": "Molducci God",
    "image": "assets/img/molduccigod.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 9,
    "tette": 9,
    "sensualita": 9,
    "intelligenza": 6,
    "maiala": 6
  },
  {
    "name": "Serena Romano",
    "image": "assets/img/serenaRomano.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 7,
    "culo": 7,
    "tette": 5,
    "sensualita": 8,
    "intelligenza": 5,
    "maiala": 9
  },
  {
    "name": "Sofi Sticata",
    "image": "assets/img/sofiSticata.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 9,
    "culo": 8,
    "tette": 5,
    "sensualita": 7,
    "intelligenza": 6,
    "maiala": 7
  },
  {
    "name": "Yarmila Mani",
    "image": "assets/img/yarmilamani.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 8,
    "tette": 7,
    "sensualita": 8,
    "intelligenza": 2,
    "maiala": 8
  },
  {
    "name": "Barboni",
    "image": "assets/img/barboni.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 7,
    "culo": 8,
    "tette": 3,
    "sensualita": 7,
    "intelligenza": 8,
    "maiala": 5
  },
  {
    "name": "Bresciani",
    "image": "assets/img/bresciani.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 8,
    "culo": 8,
    "tette": 2,
    "sensualita": 4,
    "intelligenza": 7,
    "maiala": 2
  },
  {
    "name": "Gabrielli",
    "image": "assets/img/gabrielli.jpg",
    "voto": 7,
    "faccia": 6,
    "corpo": 7,
    "culo": 6,
    "tette": 10,
    "sensualita": 6,
    "intelligenza": 3,
    "maiala": 7
  },
  {
    "name": "Galavotti",
    "image": "assets/img/galavotti.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 7,
    "culo": 7,
    "tette": 6,
    "sensualita": 6,
    "intelligenza": 7,
    "maiala": 8
  },
  {
    "name": "Levriero 2",
    "image": "assets/img/levriero2.jpg",
    "voto": 7,
    "faccia": 6,
    "corpo": 8,
    "culo": 7,
    "tette": 2,
    "sensualita": 3,
    "intelligenza": 5,
    "maiala": 8
  },
  {
    "name": "Lisa P",
    "image": "assets/img/lisap.jpg",
    "voto": 7,
    "faccia": 5,
    "corpo": 8,
    "culo": 8,
    "tette": 8,
    "sensualita": 6,
    "intelligenza": 6,
    "maiala": 10
  },
  {
    "name": "Pagliarani",
    "image": "assets/img/pagliarani.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 8,
    "tette": 8,
    "sensualita": 7,
    "intelligenza": 7,
    "maiala": 1
  },
  {
    "name": "Parisi",
    "image": "assets/img/parisi.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 8,
    "tette": 7,
    "sensualita": 8,
    "intelligenza": 8,
    "maiala": 4
  },
  {
    "name": "Sintucci",
    "image": "assets/img/sintucci.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 7,
    "culo": 7,
    "tette": 2,
    "sensualita": 6,
    "intelligenza": 7,
    "maiala": 2
  },
  {
    "name": "Zigliotto",
    "image": "assets/img/zigliotto.jpg",
    "voto": 7,
    "faccia": 8,
    "corpo": 6,
    "culo": 6,
    "tette": 4,
    "sensualita": 6,
    "intelligenza": 8,
    "maiala": 4
  },
  {
    "name": "Anna Giulia Fenati",
    "image": "assets/img/annaGiuliaFenati.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 8,
    "culo": 8,
    "tette": 2,
    "sensualita": 6,
    "intelligenza": 7,
    "maiala": 4
  },
  {
    "name": "Arianna Plazzi",
    "image": "assets/img/ariannaPlazzi.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 7,
    "culo": 6,
    "tette": 9,
    "sensualita": 5,
    "intelligenza": 6,
    "maiala": 7
  },
  {
    "name": "Ballarin",
    "image": "assets/img/ballarin.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 8,
    "tette": 2,
    "sensualita": 6,
    "intelligenza": 5,
    "maiala": 5
  },
  {
    "name": "Bojana",
    "image": "assets/img/bojana.jpg",
    "voto": 8,
    "faccia": 8,
    "corpo": 8,
    "culo": 7,
    "tette": 8,
    "sensualita": 8,
    "intelligenza": 4,
    "maiala": 6
  },
  {
    "name": "Elena Michieletti",
    "image": "assets/img/elenaMichieletti.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 7,
    "culo": 7,
    "tette": 5,
    "sensualita": 6,
    "intelligenza": 7,
    "maiala": 5
  },
  {
    "name": "Fra Bertoni",
    "image": "assets/img/fraBertoni.jpg",
    "voto": 7,
    "faccia": 7,
    "corpo": 7,
    "culo": 7,
    "tette": 5,
    "sensualita": 7,
    "intelligenza": 5,
    "maiala": 6
  },
  {
    "name": "Giorgia Berti",
    "image": "assets/img/giorgiaBerti.jpg",
    "voto": 6,
    "faccia": 5,
    "corpo": 8,
    "culo": 7,
    "tette": 8,
    "sensualita": 6,
    "intelligenza": 7,
    "maiala": 9
  },
  {
    "name": "Ivana",
    "image": "assets/img/ivana.jpg",
    "voto": 7,
    "faccia": 5,
    "corpo": 8,
    "culo": 7,
    "tette": 8,
    "sensualita": 7,
    "intelligenza": 4,
    "maiala": 7
  },
  {
    "name": "Kassandra Marrali",
    "image": "assets/img/kassandraMarrali.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 8,
    "culo": 8,
    "tette": 3,
    "sensualita": 6,
    "intelligenza": 2,
    "maiala": 5
  },
  {
    "name": "Leti96",
    "image": "assets/img/leti96.jpg",
    "voto": 8,
    "faccia": 7,
    "corpo": 8,
    "culo": 7,
    "tette": 7,
    "sensualita": 8,
    "intelligenza": 5,
    "maiala": 6
  },
  {
    "name": "Maenza",
    "image": "assets/img/maenza.jpg",
    "voto": 8,
    "faccia": 9,
    "corpo": 8,
    "culo": 7,
    "tette": 4,
    "sensualita": 7,
    "intelligenza": 2,
    "maiala": 8
  },
  {
    "name": "Margherita Model",
    "image": "assets/img/margheritaModel.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 9,
    "culo": 8,
    "tette": 7,
    "sensualita": 8,
    "intelligenza": 5,
    "maiala": 6
  },
  {
    "name": "Sofia Mihai",
    "image": "assets/img/sofiaMihai.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 8,
    "culo": 8,
    "tette": 6,
    "sensualita": 8,
    "intelligenza": 7,
    "maiala": 8
  },
  {
    "name": "Tiene",
    "image": "assets/img/tiene.jpg",
    "voto": 9,
    "faccia": 9,
    "corpo": 8,
    "culo": 8,
    "tette": 4,
    "sensualita": 8,
    "intelligenza": 4,
    "maiala": 7
  }

]





